### PR TITLE
Fixed header and stuff

### PR DESCRIPTION
**Pull request by ghost**
👋 The header was using images for the links so I downloaded them and fixed the paths in the css. Also removed .DS_Store and added it to the .gitignore :)

### CODE REVIEW

**Comment by iambenmitchell** [comment]
do be conflicting doe

**Comment by ghost** [comment]
It wasn't conflicting until 3 hours ago

**Comment by ThisIsNoahEvans** [comment]
thanks, git made all that harder than it needed to be it seems but all merged now :)

**Comment by ghost** [comment]
:)

**Pull request merged**
